[package]
name = "gpg-expire-warner"
version = "0.1.0"
authors = ["Emil Lundberg <emil@emlun.se>"]
edition = "2018"
description = "Prints a warning when GPG keys are about to expire"

[dependencies]
structopt = "0.2"
