[package]
name = "gpg-expire-warner"
version = "0.1.0"
authors = ["Emil Lundberg <emil@emlun.se>"]
edition = "2018"

[dependencies]
directories = "2.0.0"
serde = { version = "1.0.91", features = ["derive"] }
toml = "0.5.1"
